### PR TITLE
update Chinese translation

### PR DESCRIPTION
**Pull request by liangjiancang**
Updated.

This new version is very powerful. I didn't expect a browser extension to provide advanced features provided by local players like PotPlayer.

But I think the version you provided to me still has some problems. The descriptions of many functions are vague (even in English) and lack the necessary tooltips (some tooltips in the previous version are missing). For example, "pin tab", it took me a long time to figure out what it means; there is also a "cursor pointer" button in the lower right corner of the panel, which I can't figure it out at all.

### CODE REVIEW

**Comment by polywock** [comment]
Thank you! Yeah, a lot of the functions are pretty vague. I've kind of trapped myself in a corner by offering translations. It's too much work, so I prefer keeping everything short. 

The select button (cursor icon) lets the user select what video/audio they want prioritized for shortcut keys.  Useful when there are many videos on the page. Or if the user wants to control background music while in another tab. Or, if they want to control a video while using another program (using global shortcut keys).

**Comment by polywock** [comment]
I nuked the other thread. Had to stay away from sticky politics. Thanks again for the help.

**Comment by liangjiancang** [comment]
Don't be so tense, I personally don't particularly care about it. But anyway, you made a wise choice.

**Comment by polywock** [comment]
@liangjiancang, An update, one of the Chrome reviews said the Chinese translation has improved. 

Haoju Li
> Really a good extension! But the translation from English Chinese is too strange... Hope it will be better.
> 真是很不错的一个扩展程序！但是从英文到中文翻译的太奇怪了…希望可以改进得更好。
> 
> 
> 7月31日：今天我发现它更新了！界面设计更好看了些，翻译也正常了！👍  
> July 31st: Today I found out that it updated! The interface design is better, and the translation is normal! 👍

**Pull request merged**
